# Generated by Django 5.2.5 on 2025-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_booking_id_alter_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('shave', 'Shave'), ('facial', 'Facial'), ('spa', 'Spa'), ('hair_color', 'Hair Color'), ('other', 'Other')], max_length=50),
        ),
    ]
